### Make a move using Algebraic Notation.
#
# This service can also be used by a robot node (sub)system to initiate a
# physical chess move.
#
# The algebraic notation supports both Coordinate Algebraic Notation (CAN) and
# Standard Algebraic Notation (SAN).
#
# Examples:
#   "a2a4"  CAN 
#   "g8f6"  CAN
#   "Qb6"   SAN
#   "Nxc2+" SAN
#
# After making a valid chess move, the engine will automatically advance
# to the next player.
#
# The requesting player's color must match the current color's play.
#
# This service can be used to determine whether a move is valid by looking at
# the result field in the response move message. A valid move advances the play,
# however. To undo, an UndoMove request must be made to back up one ply.
#
# Note that the response time is dependent of the difficulty level of the game
# and can be very long if the search depth is deep.
#

ChessColor  player # requesting player: white or black
string      AN     # algebraic notation string
---
ChessMove move     # engine's fully qualified move
