### Get backend chess engine's move action server.

# Goal
---
# Result
ChessMoveMsg move     # engine's fully quantified move
---
# Feedback
uint16  thinking      # engine progress "thinking" in ticks
